sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO="1.10"
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"
install: pip install tox-travis
script: tox
