from django.conf.urls.defaults import *

urlpatterns = patterns('diplomacy.views',
    (r'^$', 'games_list'),
    (r'^games/$', 'games_list'),
    (r'^games/page/(?P<page>\w+)/$', 'games_list'),
    (r'^games/status/(?P<state>\w+)/$', 'games_list'),
    (r'^games/status/(?P<state>\w+)/page/(?P<page>\w+)/$', 'games_list'),
    (r'^games/name/(?P<slug>[-\w]+)/$', 'games_detail'),
    (r'^games/name/(?P<slug>[-\w]+)/join/$', 'games_join'),
    (r'^games/name/(?P<slug>[-\w]+)/turn/(?P<season>[A-Z]+)(?P<year>\d+)/$',
     'turns_detail'),
    (r'^games/name/(?P<slug>[-\w]+)/map/$', 'map_view'),
    (r'^games/name/(?P<slug>[-\w]+)/turn/(?P<season>[A-Z]+)(?P<year>\d+)/map/$',
     'map_view'),
    url(r'^games/name/(?P<slug>[-\w]+)/state/$', 'game_state',
        name="game_state"),
    url(r'^games/name/(?P<slug>[-\w]+)/turn/(?P<season>[A-Z]+)(?P<year>\d+)/state/$',
        'game_state', name="turn_state"),
    (r'^games/name/(?P<slug>[-\w]+)/orders/(?P<power>[-\w]+)/$', 'orders'),
    (r'^games/name/(?P<slug>[-\w]+)/orders/(?P<power>[-\w]+)/filter/$',
     'select_filter'),
)
